name: Code Style Checks

on:
  push:
    branches:
      - develop

env:
  node-version: "16"

jobs:

  code-style-checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.node-version }}

      - name: Install dependencies
        run: npm install --only=dev

      - name: Stop build on style violations
        run: |
          npx eslint --quiet js/**/*.js
          eslint=$?
          npx prettier --check js/**/*.js
          prettier=$?
          npx htmlhint *.html
          htmlhint=$?
          if [ $eslint -eq 0 ] && [ $prettier -eq 0 ] && [ $htmlhint -eq 0 ]; then
            echo "All style checks passed"
          else
            echo "Style checks failed - stopping build"
            echo "$eslint"
            echo "$prettier"
            echo "$htmlhint"
            exit 1
          fi

  merge-to-main:
    name: Merge to main if code-style-checks passed
    runs-on: ubuntu-latest
    needs: code-style-checks
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/develop' && needs.code-style-checks.result == 'success' }}

    steps:
      - name: Check Out Code
        uses: actions/checkout@v2
      
      - name: Merge to Main
        run: |
          git pull origin main --rebase
          git checkout main
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git merge --no-ff "develop" -m "Automated merge from develop to main"
          git push