name: Code Style Checks

on:
  push:
    branches:
      - develop

env:
  node-version: "18"

jobs:

  code-style-checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.node-version }}

      - name: Install dependencies
        run: npm install --only=dev

      - name: Stop build on style violations
        run: |
          npx eslint --quiet js/**/*.js
          eslint=$?
          npx prettier --check js/**/*.js
          prettier=$?
          npx htmlhint *.html
          htmlhint=$?
          if [ $eslint -eq 0 ] && [ $prettier -eq 0 ] && [ $htmlhint -eq 0 ]; then
            echo "All style checks passed"
          else
            echo "Style checks failed - stopping build"
            echo "$eslint"
            echo "$prettier"
            echo "$htmlhint"
            exit 1
          fi
  
  merge:
    runs-on: ubuntu-latest
    needs: code-style-checks
    steps:
      - uses: actions/checkout@v3

      - name: Merge develop -> main
        if: ${{ needs.code-style-checks.result == 'success' }} 
        uses: devmasx/merge-branch@master
        with:
          type: now
          target_branch: main
          message: "Automated merge from develop to main"
          github_token: ${{ secrets.GITHUB_TOKEN }}
